---
suites:
  - name: default
    run_list:
      - recipe[bazel::default]
  - name: package
    run_list:
      - recipe[bazel::default]
    attributes:
      bazel:
        installation_method: package
