---
driver:
  name: docker_cli
transport:
  name: docker_cli

platforms:
  - name: ubuntu-14.04
    driver_config:
      platform: ubuntu
      image: ubuntu:14.04
  - name: centos-7
    driver_config:
      platform: centos
      image: centos:7
