package(
    default_visibility = ["//visibility:public"],
)

cc_binary(
    name = "cc_hello",
    srcs = [
        "hello.cc",
    ],
)

java_binary(
    name = "java_hello",
    srcs = [
        "java/com/gengo/cookbook_bazel/test/JavaHello.java",
    ],
    main_class = "com.gengo.cookbook_bazel.test.JavaHello",
)
